name: 🧪 Test (Push)

on:
  push:
    branches:
      - main
    paths:
      - ./packages/*
      - ./.github/*
      - ./package.json
      - ./pnpm-lock.yaml
  pull_request:
    branches:
      - changeset-release/*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: github.repository == 'mcansh/remix-node-http-server'
    uses: ./.github/workflows/test.yml
    with:
      os: '["ubuntu-latest", "macos-latest", "windows-latest"]'
      node: '["18", "20", "latest"]'
